# Generated by Django 4.2.26 on 2025-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('create_date_task', models.DateTimeField(verbose_name='fecha_creacion')),
                ('finish_planned_date', models.DateTimeField(verbose_name='fecha_fin_planeada')),
                ('real_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha_fin_real')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('modificated_date', models.DateTimeField(auto_now=True, verbose_name='fecha_modificacion')),
                ('create_user', models.CharField(default='current_user', max_length=50, verbose_name='usuario_creacion')),
                ('modificate_user', models.CharField(default='current_user', max_length=50, verbose_name='usuario_modificacion')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
